# local modules
multiqc_mappings_config:
  - modules/local/multiqc_mappings_config/**
sra_fastq_ftp:
  - modules/local/sra_fastq_ftp/**
sra_ids_to_runinfo:
  - modules/local/sra_ids_to_runinfo/**
sra_merge_samplesheet:
  - modules/local/sra_merge_samplesheet/**
sra_runinfo_to_ftp:
  - modules/local/sra_runinfo_to_ftp/**
sra_to_samplesheet:
  - modules/local/sra_to_samplesheet/**

# workflow: sra
sra_custom_ena_metadata_fields:
  - modules/local/sra_ids_to_runinfo/**
  - modules/local/sra_runinfo_to_ftp/**
  - modules/local/sra_fastq_ftp/**
  - modules/local/sra_to_samplesheet/**
  - modules/local/sra_merge_samplesheet/**
  - workflows/sra/**
sra_default_parameters:
  - modules/local/sra_ids_to_runinfo/**
  - modules/local/sra_runinfo_to_ftp/**
  - modules/local/sra_fastq_ftp/**
  - modules/local/sra_to_samplesheet/**
  - modules/local/sra_merge_samplesheet/**
  - workflows/sra/**
sra_force_sratools_download:
  - modules/local/sra_ids_to_runinfo/**
  - modules/local/sra_runinfo_to_ftp/**
  - modules/local/sra_fastq_ftp/**
  - modules/local/sra_to_samplesheet/**
  - modules/local/sra_merge_samplesheet/**
  - workflows/sra/**
sra_nf_core_pipeline_atacseq:
  - modules/local/sra_ids_to_runinfo/**
  - modules/local/sra_runinfo_to_ftp/**
  - modules/local/sra_fastq_ftp/**
  - modules/local/sra_to_samplesheet/**
  - modules/local/sra_merge_samplesheet/**
  - workflows/sra/**
sra_nf_core_pipeline_rnaseq:
  - modules/local/sra_ids_to_runinfo/**
  - modules/local/sra_runinfo_to_ftp/**
  - modules/local/sra_fastq_ftp/**
  - modules/local/sra_to_samplesheet/**
  - modules/local/sra_merge_samplesheet/**
  - workflows/sra/**
sra_nf_core_pipeline_taxprofiler:
  - modules/local/sra_ids_to_runinfo/**
  - modules/local/sra_runinfo_to_ftp/**
  - modules/local/sra_fastq_ftp/**
  - modules/local/sra_to_samplesheet/**
  - modules/local/sra_merge_samplesheet/**
  - workflows/sra/**
sra_nf_core_pipeline_viralrecon:
  - modules/local/sra_ids_to_runinfo/**
  - modules/local/sra_runinfo_to_ftp/**
  - modules/local/sra_fastq_ftp/**
  - modules/local/sra_to_samplesheet/**
  - modules/local/sra_merge_samplesheet/**
  - workflows/sra/**
sra_skip_fastq_download:
  - modules/local/sra_ids_to_runinfo/**
  - modules/local/sra_runinfo_to_ftp/**
  - modules/local/sra_fastq_ftp/**
  - modules/local/sra_to_samplesheet/**
  - modules/local/sra_merge_samplesheet/**
  - workflows/sra/**
