# local modules
multiqc_mappings_config:
  - modules/local/multiqc_mappings_config/*
sra_fastq_ftp:
  - modules/local/sra_fastq_ftp/*
sra_ids_to_runinfo:
  - modules/local/sra_ids_to_runinfo/*
sra_merge_samplesheet:
  - modules/local/sra_merge_samplesheet/*
sra_runinfo_to_ftp:
  - modules/local/sra_runinfo_to_ftp/*
sra_to_samplesheet:
  - modules/local/sra_to_samplesheet/*

# workflow: sra
sra_custom_ena_metadata_fields:
  - conf/modules/sra.config
  - modules/local/sra_ids_to_runinfo/main.nf
  - modules/local/sra_runinfo_to_ftp/main.nf
  - modules/local/sra_fastq_ftp/main.nf
  - modules/local/sra_to_samplesheet/main.nf
  - modules/local/sra_merge_samplesheet/main.nf
  - workflows/sra/main.nf
  - workflows/sra/tests/sra_custom_ena_metadata_fields.nf.test
sra_default_parameters:
  - conf/modules/sra.config
  - modules/local/sra_ids_to_runinfo/main.nf
  - modules/local/sra_runinfo_to_ftp/main.nf
  - modules/local/sra_fastq_ftp/main.nf
  - modules/local/sra_to_samplesheet/main.nf
  - modules/local/sra_merge_samplesheet/main.nf
  - workflows/sra/main.nf
  - workflows/sra/tests/sra_default_parameters.nf.test
sra_force_sratools_download:
  - conf/modules/sra.config
  - modules/local/sra_ids_to_runinfo/main.nf
  - modules/local/sra_runinfo_to_ftp/main.nf
  - modules/local/sra_fastq_ftp/main.nf
  - modules/local/sra_to_samplesheet/main.nf
  - modules/local/sra_merge_samplesheet/main.nf
  - workflows/sra/main.nf
  - workflows/sra/tests/sra_force_sratools_download.nf.test
sra_nf_core_pipeline_atacseq:
  - conf/modules/sra.config
  - modules/local/sra_ids_to_runinfo/main.nf
  - modules/local/sra_runinfo_to_ftp/main.nf
  - modules/local/sra_fastq_ftp/main.nf
  - modules/local/sra_to_samplesheet/main.nf
  - modules/local/sra_merge_samplesheet/main.nf
  - workflows/sra/main.nf
  - workflows/sra/tests/sra_nf_core_pipeline_atacseq.nf.test
sra_nf_core_pipeline_rnaseq:
  - conf/modules/sra.config
  - modules/local/sra_ids_to_runinfo/main.nf
  - modules/local/sra_runinfo_to_ftp/main.nf
  - modules/local/sra_fastq_ftp/main.nf
  - modules/local/sra_to_samplesheet/main.nf
  - modules/local/sra_merge_samplesheet/main.nf
  - workflows/sra/main.nf
  - workflows/sra/tests/sra_nf_core_pipeline_rnaseq.nf.test
sra_nf_core_pipeline_taxprofiler:
  - conf/modules/sra.config
  - modules/local/sra_ids_to_runinfo/main.nf
  - modules/local/sra_runinfo_to_ftp/main.nf
  - modules/local/sra_fastq_ftp/main.nf
  - modules/local/sra_to_samplesheet/main.nf
  - modules/local/sra_merge_samplesheet/main.nf
  - workflows/sra/main.nf
  - workflows/sra/tests/sra_nf_core_pipeline_taxprofiler.nf.test
sra_nf_core_pipeline_viralrecon:
  - conf/modules/sra.config
  - modules/local/sra_ids_to_runinfo/main.nf
  - modules/local/sra_runinfo_to_ftp/main.nf
  - modules/local/sra_fastq_ftp/main.nf
  - modules/local/sra_to_samplesheet/main.nf
  - modules/local/sra_merge_samplesheet/main.nf
  - workflows/sra/main.nf
  - workflows/sra/tests/sra_nf_core_pipeline_viralrecon.nf.test
sra_skip_fastq_download:
  - conf/modules/sra.config
  - modules/local/sra_ids_to_runinfo/main.nf
  - modules/local/sra_runinfo_to_ftp/main.nf
  - modules/local/sra_fastq_ftp/main.nf
  - modules/local/sra_to_samplesheet/main.nf
  - modules/local/sra_merge_samplesheet/main.nf
  - workflows/sra/main.nf
  - workflows/sra/tests/sra_skip_fastq_download.nf.test
