repository_type: pipeline
lint:
  actions_ci: false
  files_exist:
    - conf/modules.config
    - lib/NfcoreTemplate.groovy
    - lib/Utils.groovy
    - lib/WorkflowMain.groovy
    - lib/nfcore_external_java_deps.jar
  files_unchanged:
    - .gitignore
    - assets/sendmail_template.txt
