repository_type: pipeline
lint:
  actions_ci: false
  files_exist:
    - .github/workflows/awsfulltest.yml
    - .github/workflows/awstest.yml
    - assets/multiqc_config.yml
    - conf/igenomes.config
    - conf/modules.config
    - lib/NfcoreTemplate.groovy
    - lib/Utils.groovy
    - lib/WorkflowFetchngs.groovy
    - lib/WorkflowMain.groovy
    - lib/nfcore_external_java_deps.jar
  files_unchanged:
    - .gitattributes
    - .gitignore
    - assets/sendmail_template.txt
    - lib/NfcoreTemplate.groovy
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md                                         │
    - .github/workflows/linting.yml
