name: nf-core CI
# This workflow runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
      - master
  release:
    types: [published]

env:
  NXF_ANSI_LOG: false

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  test-dev:
    # Only run on dev branch or when a PR is opened against dev
    if: github.base_ref == 'dev' || github.event_name == 'push'
    name: Run pipeline with test data on dev
    runs-on: ubuntu-latest
    # Define the matrix of different Nextflow versions to test
    strategy:
      matrix:
        NXF_VER: ["latest-everything"]
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v3

      # Install Nextflow
      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: "${{ matrix.NXF_VER }}"

      # Install nf-test
      - name: Install nf-test
        run: |
          wget -qO- https://code.askimed.com/install/nf-test | bash
          sudo mv nf-test /usr/local/bin/

      # Run nf-test
      - name: Run nf-test
        run: nf-test test tests/pipeline/ --tap=test.tap

      # If the test fails, output the software_versions.yml using the 'batcat' utility
      - name: Output log on failure
        if: failure()
        run: |
          sudo apt install bat > /dev/null
          batcat --decorations=always --color=always /home/runner/work/fetchngs/fetchngs/.nf-test/tests/*/output/pipeline_info/software_versions.yml

      # Comment on the PR with the test results
      - name: PR comment with file
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: test.tap

  test-master:
    # Only run on master branch or when a PR is opened against master
    if: github.base_ref == 'master'
    name: Run pipeline with test data on master
    runs-on: ubuntu-latest
    # Define the matrix of different Nextflow versions to test
    strategy:
      matrix:
        NXF_VER: ["22.10.1", "latest-everything"]
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v3

      # Install Nextflow
      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: "${{ matrix.NXF_VER }}"

      # Install nf-test
      - name: Install nf-test
        run: |
          wget -qO- https://code.askimed.com/install/nf-test | bash
          sudo mv nf-test /usr/local/bin/

      # Run nf-test
      - name: Run nf-test
        run: nf-test test tests/pipeline/ --tap=test.tap

      # If the test fails, output the software_versions.yml using the 'batcat' utility
      - name: Output log on failure
        if: failure()
        run: |
          sudo apt install bat > /dev/null
          batcat --decorations=always --color=always /home/runner/work/fetchngs/fetchngs/.nf-test/tests/*/output/pipeline_info/software_versions.yml

      # Comment on the PR with the test results
      - name: PR comment with file
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: test.tap
