name: nf-core CI

on:
  pull_request:
    branches:
      - dev
  release:
    types: [published]

env:
  NXF_ANSI_LOG: false

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  get_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v3

      - name: Get Minimum supported Nextflow version
        id: get_version
        run: |
          VERSION=$(grep 'nextflowVersion' nextflow.config | awk -F'= ' '{print $2}' | tr -d '!>=" ')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

  test:
    name: Run ${{ matrix.profile }} pipeline test
    needs: get_version

    if: "${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'nf-core/fetchngs') }}"

    runs-on: ubuntu-latest
    env:
      NXF_VER: ${{ needs.get_version.outputs.version }}

    strategy:
      matrix:
        profile: ["docker"]

    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v3

      - name: Use Nextflow version
        run: echo "Using Nextflow version $NXF_VER"

      - name: Cache test data
        uses: actions/cache@v2
        with:
          path: /usr/local/bin/nextflow
          key: ${{ runner.os }}
          restore-keys: ${{ runner.os }}-nextflow-

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: ${{ matrix.NXF_VER }}

      - name: Install nf-test
        run: |
          wget -qO- https://code.askimed.com/install/nf-test | bash
          sudo mv nf-test /usr/local/bin/

      - name: Run nf-test
        run: nf-test test tests/pipeline/ --tap=test.tap

      # If the test fails, output the software_versions.yml using the 'batcat' utility
      - name: Output log on failure
        if: failure()
        run: |
          sudo apt install bat > /dev/null
          batcat --decorations=always --color=always /home/runner/work/fetchngs/fetchngs/.nf-test/tests/*/output/pipeline_info/software_versions.yml

      - uses: pcolby/tap-summary@v1
        with:
          path: test.tap
