name: wgs-bact CI

on:
  pull_request: # Trigger on pull requests

jobs:
  test:
    name: Run Pipeline Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER:
          - "latest-everything" # Test with the latest Nextflow version
        profile:
          - "docker" # Run tests using the docker profile

    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v4 # Standard action to get your code

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1 # Standard action to install Nextflow
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Run pipeline with example SRR accession
        run: |
          echo "SRR9984183" > ids.csv
          nextflow run main.nf -profile docker,ci --input ids.csv --outdir results_srr_test -stub # Use -stub for a quick test without actual data download/processing

  functional_test:
    name: Run Functional Test
    runs-on: ubuntu-latest
    needs: test # Ensure this runs after the stubbed test
    strategy:
      matrix:
        NXF_VER:
          - "latest-everything"
        profile:
          - "docker"

    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v4

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Run pipeline with test dataset
        run: |
          nextflow run main.nf \
            -profile ${{ matrix.profile }},test \
            --outdir results_functional_test

      - name: Check for expected output files
        run: |
          # Replace with actual expected output files from your pipeline
          # For example, check for a multiqc report or trimmed fastq files
          ls -l results_functional_test/multiqc/multiqc_report.html
          ls -l results_functional_test/fastp/*trimmed.fastq.gz
