name: wgs-bact CI

on:
  pull_request: # Trigger on pull requests

jobs:
  test:
    name: Run Pipeline Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER:
          - "latest-everything" # Test with the latest Nextflow version
        profile:
          - "docker" # Run tests using the docker profile
        tags: ["pipeline"] # Explicitly run only the 'pipeline' test

    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v4 # Standard action to get your code

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1 # Standard action to install Nextflow
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Install nf-test
        run: | # Install nf-test directly
          wget -qO- https://code.askimed.com/install/nf-test | bash
          sudo mv nf-test /usr/local/bin/

      - name: Run nf-test
        run: | # Execute the pipeline test
          nf-test test --verbose --tag ${{ matrix.tags }} --profile "+${{ matrix.profile }}"