name: Test successful pipeline download

on: [pull_request]

jobs:
  download:
    name: Test successful pipeline download with 'nf-core download'
    runs-on: ubuntu-latest
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v4

      - name: Install nf-core tools
        run: pip install nf-core

      - name: Run nf-core download
        run: |
          nf-core download ${{ github.repository }} \
            --revision ${{ github.head_ref }} \
            --outdir ./wgs-bact \
            --compress "none" \
            --container-system 'singularity' \
            --container-library "quay.io" -l "docker.io" -l "ghcr.io" \
            --container-cache-utilisation 'amend' \
            --download-configuration
